config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  devise_for :users

  resources :events
  resources :users, only: [:index, :create, :update]

  # routes for creating and removing attendees
  post '/events/:id/attend', to: 'events#attend', as: 'attend_event'
  delete 'events/:id/unattend', to: 'events#unattend', as: 'unattend_event'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  has_many :event_attendees
  has_many :attendees, through: :event_attendees, source: :user

  validates :title, presence: true
  validates :description, presence: true
  validates :location, presence: true
  validates :date, presence: true
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_events, class_name: 'Event', foreign_key: 'user_id'
  has_many :event_attendees
  has_many :attended_events, through: :event_attendees, source: :event

  validates :name, presence: true
  validates :email, presence: true
  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)

    if @event.save
      redirect_to events_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to events_path, notice: 'event is being updated'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def attend
    @event = Event.find(params[:id])
    current_user.attended_events << @event
    redirect_to @event, notice: 'you are now attending this event'
  end

  def unattend
    @event = Event.find(params[:id])
    current_user.attended_events.delete(@event)
    redirect_to @event, notice: 'you have successfully unattended this event'
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :date, :location)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>List of events</h1>

<% @events.each do |event| %>
  <h2><%= event.title %></h2>
  <p><%= event.description %></p>
  <p><%= event.location %></p>
  <p><%= event.date %></p>

  <% if !current_user.nil?%>
    <% if current_user&.attended_events.include?(event) %>
    <%= link_to 'Unattend', unattend_event_path(event), data: { turbo_method: :delete} %>
    <% else %>
    <%= link_to 'Attend', attend_event_path(event), data: { turbo_method: :post} %>
    <% end %>
  <% end %>
<% end %>
<% if !current_user.nil?%>
  <div>
    <br>
    <%= link_to 'Create an event', new_event_path %>
  </div>
<% end %>

app/views/events/new.html.erb
<h1>Create an event</h1>

<%= form_with model: @event do |f| %>
  <div>
    <%= f.label :title, "Title: "%>
    <%= f.text_field :title, placeholder: "Enter event title"%>
  </div>

  <div>
    <%= f.label :description, "Description: "%>
    <%= f.text_field :description, placeholder: "Enter event description"%>
  </div>

  <div>
    <%= f.label :location, "Location: "%>
    <%= f.text_field :location, placeholder: "Enter event location"%>
  </div>

  <div>
    <%= f.label :date, "Date: "%>
    <%= f.datetime_field :date, placeholder: "Enter event description"%>
  </div>
  
  <%= f.submit "Create event", disable_with: 'Creating event...'%>
<% end %>

app/views/events/show.html.erb
<div>
  <h2><%= @event.title %></h2>
  <p><%= @event.description %></p>
  <p><%= @event.location %></p>
  <p><%= @event.date %></p>
</div>

<%= link_to 'All events', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div id="user_nav">
      <% if user_signed_in? %>
          Signed in as <%= current_user.email %>. This cannot be cheese?
            <%= link_to "Logout", destroy_user_session_path, data: {
              turbo_method: :delete,
              turbo_confirm: "Estas seguro de cerrar sesion?"
              } %>
      <% else %>
          <%= link_to 'Register', new_user_registration_path %> or <%= link_to 'Sign in', new_user_session_path %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>